### PR TITLE
h5ad processing

### PR DESCRIPTION
**Pull request by aopisco**
this branch contains:

- processing.py
-- the script for processing the data if in h5ad format already

- adata_small_test.h5ad
-- test file to use as input

### CODE REVIEW

**Comment by aopisco** [comment]
> * I am reluctant to check in files these large. Do they exist on some URL developers could download from?

yes and I agree, I just put it here for now but I can rather upload it to GDrive?

**Comment by mccalluc** [comment]
> yes and I agree, I just put it here for now but I can rather upload it to GDrive?

Yes, that would be good, or s3, or whatever: git keeps a full history of all changes, so if we merged this with the files in place, a checkout of the repo would always include them as part of the history, even if we later got rid of them in `master`.

**Comment by aopisco** [comment]
> > yes and I agree, I just put it here for now but I can rather upload it to GDrive?
> 
> Yes, that would be good, or s3, or whatever: git keeps a full history of all changes, so if we merged this with the files in place, a checkout of the repo would always include them as part of the history, even if we later got rid of them in `master`.

We now have a data directory and I'm updating the instructions.sh file

**Comment by aopisco** [comment]
@mccalluc I think we're ready to merge

**Pull request merged**
